# TESTING WAREHOUSE"Flooring_id"
###


GET http://localhost:3000/floorings HTTP/1.1
content-type: application/json
###

GET http://localhost:3000/floorings/65f5cd95cbe8b25154edc159 HTTP/1.1
content-type: application/json
###

POST http://localhost:3000/floorings/65f5cd95cbe8b25154edc159 HTTP/1.1
content-type: application/json

{
                "Name": "theTHING",
                "Description": "WALL",
                "Price": "Price",
                "Category": "Category",
                "Stock": 45,
                "Manufacturer": "dudething",
                "date_added": "date_added",
                "Weight_kg": 34,
                "Product_id": 24
}
###
PUT http://localhost:3000/floorings/create HTTP/1.1
content-type: application/json

{
                "Name": "TEST",
                "Description": "THING",
                "Price": "Price",
                "Category": "Category",
                "Stock": 45,
                "Manufacturer": "Manufacturer",
                "date_added": "date_added",
                "Weight_kg": 34,
                "Product_id": 24
}
###
DELETE http://localhost:3000/floorings/65f5cd43cbe8b25154edc158 HTTP/1.1
content-type: application/json




# TESTING CUSTOMER
###
GET http://localhost:3000/customers/ HTTP/1.1
content-type: application/json
###



GET http://localhost:3000/customers/65fb5306bb2dc7041c331748 HTTP/1.1
content-type: application/json
###



POST http://localhost:3000/customers/65fb5306bb2dc7041c331748 HTTP/1.1
content-type: application/json

{
                "firstName": "NiCk",
                "lastName": "RiCaRdS",
                "email": "example@email.com",
                "phoneNumber": 555555555
}

###


PUT http://localhost:3000/customers/create HTTP/1.1
content-type: application/json

{
                "firstName": "tester",
                "lastName": "rester",
                "email": "example@email.com",
                "phoneNumber": 777777777
}


###
DELETE http://localhost:3000/customers/65fb57cb324624a393f5c8d4 HTTP/1.1
content-type: application/json



















# ###
# # RENDER PROD TESTING


# GET https://library-wkyz.onrender.com/books HTTP/1.1
# content-type: application/json
# ###



# GET https://library-wkyz.onrender.com/books/65c6b153471d16e6f273725d HTTP/1.1
# content-type: application/json
# ###



# POST https://library-wkyz.onrender.com/books/65c6b153471d16e6f273725d HTTP/1.1
# content-type: application/json

# {
#                 "Name": "Name",
#                 "Description": "Description",
#                 "Price": "Price",
#                 "Category": "Category",
#                 "Stock": "Stock",
#                 "Manufacturer": "Manufacturer",
#                 "date_added": "date_added",
#                 "Weight_kg": "Weight_kg",
#                 "Product_id": "Product_id"
# }

# ###


# PUT https://library-wkyz.onrender.com/books/create HTTP/1.1
# content-type: application/json

# {
#                 "Name": "Name",
#                 "Description": "Description",
#                 "Price": "Price",
#                 "Category": "Category",
#                 "Stock": "Stock",
#                 "Manufacturer": "Manufacturer",
#                 "date_added": "date_added",
#                 "Weight_kg": "Weight_kg",
#                 "Product_id": "Product_id"
# }


# ###
# DELETE https://library-wkyz.onrender.com/books/65b5c7ed8d64a476bba785e0 HTTP/1.1
# content-type: application/json